module.exports = {
    nameIsShort: '"displayName" length must be at least 8 characters long',
    emailIsWrongFormat: '"email" must be a valid email',
    emailRequired: '"email" is required',
    passwordShorterThan: '"password" length must be 6 characters long',
    passwordRequired: '"password" is required',
    userAlreadyExists: 'User already registered',
    invalidEmail: 'User already registered',
    invalidFields: 'Invalid fields',
    emailCannotBeEmpty: '"email" is not allowed to be empty',
    passwordCannotBeEmpty: '"password" is not allowed to be empty',
    tokenNotFound: 'Token not found',
    invalidToken: 'Expired or invalid token',
    userDoesNotExists: 'User does not exist',
};